#!/bin/bash
# Dotplane — agent-only install for additional servers
#
# Usage:
#   curl -fsSL "https://platform/${URL_KEY}/agent-install/${TOKEN}" | sudo bash
#   curl -fsSL "https://platform/${URL_KEY}/agent-install/${TOKEN}" | sudo DOTPLANE_PLATFORM_URL=https://platform bash
#
# TOKEN is a one-time registration token generated by the Platform UI.

set -euo pipefail

RED='\033[0;31m'
GREEN='\033[0;32m'
BLUE='\033[0;34m'
NC='\033[0m'

log()  { echo -e "${BLUE}[dotplane-agent]${NC} $1"; }
ok()   { echo -e "${GREEN}[✓]${NC} $1"; }
fail() { echo -e "${RED}[✗]${NC} $1"; exit 1; }

[[ $EUID -ne 0 ]] && fail "Run as root"
[[ "$(uname -s)" != "Linux" ]] && fail "Linux only"

REGISTRATION_TOKEN="${1:-${DOTPLANE_REGISTRATION_TOKEN:-}}"
PLATFORM_URL="${2:-${DOTPLANE_PLATFORM_URL:-}}"

[[ -z "$REGISTRATION_TOKEN" ]] && fail "No registration token — use: curl ... | sudo bash -s -- TOKEN PLATFORM_URL"
[[ -z "$PLATFORM_URL" ]] && fail "No platform URL — set DOTPLANE_PLATFORM_URL or pass as second argument"

AGENT_ROOT="/opt/dotplane-agent"
NODE_VERSION="${NODE_VERSION:-20}"

# ── 1. System dependencies ─────────────────────────────────────────────────────
log "Installing system dependencies..."
export DEBIAN_FRONTEND=noninteractive
apt-get update -qq
apt-get install -y -qq curl wget unzip rsync openssl ca-certificates systemd jq

# ── 2. Node.js via fnm ───────────────────────────────────────────────────────
log "Installing Node.js ${NODE_VERSION} via fnm..."
if ! command -v fnm >/dev/null 2>&1; then
  curl -fsSL https://fnm.vercel.app/install | bash -s -- --install-dir /usr/local --skip-shell
fi
export PATH="/usr/local/bin:${PATH}"
eval "$(fnm env --shell bash)"
fnm install "$NODE_VERSION"
fnm default "$NODE_VERSION"
NODE_BIN="$(fnm which node)"
ok "Node $($NODE_BIN --version)"

# ── 3. Caddy (prebuilt — required for instance routes) ─────────────────────────
# NOTE: For custom modules, rebuild with xcaddy (see scripts/install.sh).
log "Installing Caddy..."
ARCH="$(uname -m)"
case "$ARCH" in
  x86_64)  CADDY_ARCH="amd64" ;;
  aarch64) CADDY_ARCH="arm64" ;;
  *)       fail "Unsupported architecture: $ARCH" ;;
esac
if [[ ! -x /usr/local/bin/caddy ]]; then
  curl -fsSL "https://caddyserver.com/api/download?os=linux&arch=${CADDY_ARCH}" \
    -o /usr/local/bin/caddy
  chmod +x /usr/local/bin/caddy
fi

if [[ ! -f /etc/systemd/system/caddy.service ]]; then
  cat > /etc/systemd/system/caddy.service << 'EOF'
[Unit]
Description=Caddy
After=network.target

[Service]
ExecStart=/usr/local/bin/caddy run --config /etc/caddy/Caddyfile --resume
ExecReload=/usr/local/bin/caddy reload --config /etc/caddy/Caddyfile
Restart=on-failure
User=caddy
Group=caddy
AmbientCapabilities=CAP_NET_BIND_SERVICE

[Install]
WantedBy=multi-user.target
EOF
  useradd -r -s /bin/false caddy 2>/dev/null || true
  mkdir -p /etc/caddy /var/lib/caddy
  chown -R caddy:caddy /var/lib/caddy

  cat > /etc/caddy/Caddyfile << 'EOF'
{
    admin localhost:2019
    persist_config on
}
EOF
  systemctl enable caddy
  systemctl start caddy
fi
ok "Caddy ready"

# ── 4. .NET SDK ────────────────────────────────────────────────────────────────
log "Installing .NET 8 SDK..."
curl -fsSL https://dot.net/v1/dotnet-install.sh -o /tmp/dotnet-install.sh
chmod +x /tmp/dotnet-install.sh
/tmp/dotnet-install.sh --channel 8.0 --install-dir /usr/share/dotnet --no-path
ln -sf /usr/share/dotnet/dotnet /usr/local/bin/dotnet 2>/dev/null || true
ok ".NET $(/usr/share/dotnet/dotnet --version)"

# ── 5. Download agent bootstrap bundle from Platform ───────────────────────────
log "Downloading agent bootstrap bundle..."
mkdir -p "${AGENT_ROOT}/certs"
chmod 700 "${AGENT_ROOT}" "${AGENT_ROOT}/certs"

BOOTSTRAP_URL="${PLATFORM_URL%/}/api/agent-bootstrap/${REGISTRATION_TOKEN}"
curl -fsSL "$BOOTSTRAP_URL" -o /tmp/agent-bootstrap.tar.gz
tar -xzf /tmp/agent-bootstrap.tar.gz -C "$AGENT_ROOT/"
rm -f /tmp/agent-bootstrap.tar.gz
chmod 600 "${AGENT_ROOT}/certs"/*.key 2>/dev/null || true
chmod 600 "${AGENT_ROOT}/.env" 2>/dev/null || true
ok "Agent bundle extracted"

# ── 6. Instance data directories ───────────────────────────────────────────────
mkdir -p /var/dotplane/instances /var/dotplane/artifacts
chmod 755 /var/dotplane

# ── 7. systemd template unit for .NET apps ─────────────────────────────────────
if [[ -f "${AGENT_ROOT}/systemd/dotnet-app@.service" ]]; then
  cp "${AGENT_ROOT}/systemd/dotnet-app@.service" /etc/systemd/system/
elif [[ -f /opt/dotplane/systemd/dotnet-app@.service ]]; then
  cp /opt/dotplane/systemd/dotnet-app@.service /etc/systemd/system/
else
  fail "dotnet-app@.service template not found in bootstrap bundle"
fi

# ── 8. Agent systemd service ───────────────────────────────────────────────────
AGENT_ENTRY="${AGENT_ROOT}/dist/index.js"
[[ -f "$AGENT_ENTRY" ]] || AGENT_ENTRY="${AGENT_ROOT}/packages/agent/dist/index.js"

cat > /etc/systemd/system/dotplane-agent.service << EOF
[Unit]
Description=Dotplane Agent
After=network.target caddy.service

[Service]
Type=simple
WorkingDirectory=${AGENT_ROOT}
ExecStart=${NODE_BIN} ${AGENT_ENTRY}
Restart=always
RestartSec=5
User=root
EnvironmentFile=${AGENT_ROOT}/.env
Environment=PATH=/usr/local/bin:/usr/share/dotnet:/usr/bin:/bin

[Install]
WantedBy=multi-user.target
EOF

systemctl daemon-reload
systemctl enable dotplane-agent
systemctl start dotplane-agent
ok "Dotplane Agent running"

echo ""
echo -e "${GREEN}Dotplane Agent installed and running.${NC}"
echo "Waiting for Platform to confirm registration (check Servers page)."
